version = 0.1

[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "fitforge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-fitforge"
s3_prefix = "fitforge"
region = "us-west-2"
confirm_changeset = false
capabilities = "CAPABILITY_IAM CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
parameter_overrides = []
profile = "prod-account"